# The URL the site will be built for
base_url = "https://example.com"

theme = "terminimal"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# colouring, 5 options from the theme and two options of dark and gray brackground
accent_color = "red"
background_color = "dark"

# logo
logo_text = "lunarian vignettes, and other related snippets"

# author at bottom page
author = "rumi"

# Whether to show links to earlier and later posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Read more"

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "pieces", url = "$BASE_URL"},
    
    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    {name = "twitter", url = "https://twitter.com/lxyn_fanboy", newtab = true},
    
    # set newtab to true to make the link open in new tab
    {name = "github", url = "https://github.com/dichromatic", newtab = true},
]
